### PR TITLE
Polish PML 3.0.0 Changelog

### PR DESCRIPTION
**Pull request by tajmone**
Adjust the Changelog by rephrasing various sentences and
fixing some expressions in order to bring the text closer
to idiomatic English and/or render it smoother to read.

### CODE REVIEW

**Comment by tajmone** [comment]
Please note that in a couple of places I've taken the liberty to rephrase some sentences that were unclear, opting to spell out in a clear manner what I _assumed_ to be the most obvious understanding of these sentences.

Please check the following changes to ensure that I've got them right (if I didn't, one more reason to fix their original text).


## New Binaries

Original text:

> Windows/Linux installers are no more supported. They have been replaced by standalone binary executables, as well as Java jar executables that can run on Windows, Linux, and MacOS systems with a JavaRuntime Environment (JRE) installed.

Changed to:

> Windows/Linux installers are no longer supported. They have been replaced by OS-specific standalone binary executables or, alternatively, a cross-platform Java jar executable that can be run on Windows, Linux, and MacOS systems where the JavaRuntime Environment (JRE) has been installed.

I'm assuming that the "portable binary executables" are OS-specific (a different file for each OS), whereas the Java distribution is cross-platform (a single `zip` or `tar.gz` for all OSs).

## New `position` Field

Original text:

> Field `position` has been added for attributes (as a replacement for `default_attribute_id` and a more versatile field for future improvements).

Changed to:

> The `position` field has been added to attributes as a replacement for `default_attribute_id`, which is more versatile for future improvements.

I'm assuming that the words "a more versatile field for future improvements" referred to the `position` field, i.e. not to another new (unmentioned) field that was also introduced in PML 3.

**Comment by pml-lang** [comment]
Thanks. Much appreciated!

> I'm assuming that the "portable binary executables" are OS-specific (a different file for each OS), whereas the Java distribution is cross-platform (a single zip or tar.gz for all OSs).

Yes, correct.

> I'm assuming that the words "a more versatile field for future improvements" referred to the position field, i.e. not to another new (unmentioned) field that was also introduced in PML 3.

Yes.

**Comment by tajmone** [comment]
Please, **DON'T** merge-commit PRs: you loose all the commit info of the message making the repo history hard to read.
Instead merge with rebase!

GitHub by default merges with a commit but you can change the repo setting (and even your global account setings for the defaults of every new repo) so that it will by default offer rebase-merging in the WebUI merge button. You can also disable commit-merges altogether, to enforce a linear history.

If you could fix the PR commit, either via rewrite operations or at least by editing the commit message to preserve its original text I'd really appreciate it.

**Comment by pml-lang** [comment]
> Please, DON'T merge-commit PRs

Sorry.

> you can change the repo setting

Done.

> If you could fix the PR commit

Will try to do that later.

**Pull request merged**
