### PR TITLE
EditorConfig Settings

### PR DESCRIPTION
**Pull request by tajmone**
Improve repository settings to enforce consistent code styles across
different OSs and editors by adding EditorConfig rules and tweaking
Git configurations:

* New `.editorconfig` and `.gitattributes` configuration files to
  enforce consistent code style rules for:
    * Repository configuration files.
    * Plain-text and LICENSE files.
    * Shell and batch scripts.
    * Markdown document.
    * PML documents.
* Add to `.gitignore` new rules to cover common OSs and application
  temporary files that are likely to occur on end users machines.

These settings will reduce noise in commits and PRs by avoiding
spurious whitespace changes enforced by custom editor settings
(conversion of spaces to tabs, etc.) ending up in new commits and
pull requests, restricting them to actual contents changes.

### CODE REVIEW

**Comment by tajmone** [comment]
Lacking contributor's guidelines, I opted to create this PR directly on `main` branch, reasoning that it would make sense that after merging it you then rebase the dev branch on main and force push it, since these new settings should apply to all branches.

In the PR I didn't actually enforce code styles consistency (many files fail the EditorConfig validation test) by tweaking all the sources (trim trailing spaces, add empty line at end, etc.) because I believe that the main goal here is to ensure that in the future these styling rules will be enforced on the project, i.e. to keep commits and PRs noise-free, but that there's no need to strictly enforce them all at once — i.e. the repository will eventually meet the consistency criteria once all files have been edited and saved at least once, which I believe is going to eventually happen since when the PML syntax changes you have to tweak the older Changelog files too. 

Furthermore, there's no point in being strict about styles unless their validation is enforced on commits and PRs via some CI script.

Having said that, If you prefer me to create a new PR (or amend this one) where all source files are aesthetically fixed so they pass EditorConfig validation just let me know.

**Comment by pml-lang** [comment]
> I opted to create this PR directly on main branch

As there is now a `develop` branch, no PRs should be done in the `main` branch (to avoid merge conflicts that can be difficult to manage). I will merge `develop` into `main` later when PMLC 3 is published.

> If you prefer me to create a new PR (or amend this one) where all source files are aesthetically fixed.

I would appreciate a new PR on the `develop` branch (to replace this PR on the `main` branch). I agree that fixing all source files aesthetically is not required, although it would be a 'nice to have'. In the future I'll be more careful to apply code styles in my editor.

**Comment by tajmone** [comment]
> As there is now a `develop` branch, no PRs should be done in the `main` branch (to avoid merge conflicts that can be difficult to manage). I will merge `develop` into `main` later when PMLC 3 is published.
> 
> I would appreciate a new PR on the `develop` branch (to replace this PR on the `main` branch).

I'll do that. But in this case, with two PRs being created at once, creating this PR on `main` was the best option since (if you had rebase-merged the PR on the dev branch) rebasing `develop` on `main` (after accepting both PRs) would have been a straight-forward and conflict-free operations.

Anyway, I'll replay the changes on `develop`, there aren't a lot changes at stake here so it should be straight forward.

**Comment by tajmone** [comment]
This PR was recreated at #4.

**Pull request closed without merging**
