### PR TITLE
Editor Config Styles Consistency

### PR DESCRIPTION
**Pull request by tajmone**
This PR contains two commits:

# EditorConfig Settings

Improve repository settings to enforce consistent code styles across
different OSs and editors by adding EditorConfig rules and tweaking
Git configurations:

* New `.editorconfig` and `.gitattributes` configuration files to
  enforce consistent code style rules for:
    * Repository configuration files.
    * Plain-text and LICENSE files.
    * Shell and batch scripts.
    * Markdown document.
    * PML documents.
* Add to `.gitignore` new rules to cover common OSs and application
  temporary files that are likely to occur on end users machines.

These settings will reduce noise in commits and PRs by avoiding
spurious whitespace changes enforced by custom editor settings
(conversion of spaces to tabs, etc.) ending up in new commits and
pull requests, restricting them to actual contents changes.

# Enforce Code Styles Consistency

* Apply cosmetic tweaks to all source files that failed to pass
  EditorConfig styles consistency validation.
* `README.md`:
    * Fix some markdown formatting errors.
    * Polish a couple of sentences.
    * Convert inline-links to reference labels placed at the
      end of the document, and add descriptive title text to
      be show on link hovering.

### CODE REVIEW

**Comment by pml-lang** [comment]
Thanks.

**Comment by pml-lang** [comment]
I suppose that the following line in file `.gitattributes`:
```
*.com   text eol=crlf
```
... should be:
```
*.cmd   text eol=crlf
```
Could you confirm please? I will then change it in my local `develop` branch.

**Comment by tajmone** [comment]
> Could you confirm please?

Don't worry about that, it's just for safety — that extension is rarely used, but since it came up in a couple of projects (e.g. when including old MS scripts) I've just added the definition to ensure correct CRLF end-of-lines would be used at Git check-in. 

Bear in mind that for speed purposes when I create repository settings like these I use some custom snippets to quickly inject the rules for specific file types, so these snippet templates tend to contain more extensions than I actually end using, i.e. also alternative extensions that might be encountered in third party modules. Even if I don't use these extensions I just keep them there, can't bother editing the snippet output (more is harmless).

As for the `.cmd` extension ... should I also add it to the batch files extensions in my repository settings? I haven't seen that extension used either, which is why I've omitted it from my settings templates. The reason I've included the `.com` extension is because I've seen it used in some MS scripts (e.g. old SDKs, etc.).

**Comment by pml-lang** [comment]
As far as I know:
- the [com](https://fileinfo.com/extension/com) extension is used for _binary_ executable files (introduced in DOS)
- the [cmd](https://fileinfo.com/extension/cmd) extension is used for _text_ files that contain Windows scripts (like `bat` files)  .

Therefore IMO `com` should be replaced with `cmd` in file `.gitattributes`.

That would also be consistent with the following line in file `.editorconfig`:
```
s [*.{bat,cmd}]
```

To be complete, we should also add `ps1` (file extension for PowerShell script file) in  `.gitattributes` and `.editorconfig`.

**Comment by tajmone** [comment]
> - the com extension is used for binary executable files (introduced in DOS)

I'm aware of that, but the reason I've added it to my templates was because I actually stumbled upon it in some real projects. After some discussions with its participants, we decided to add the definition of `.com` as a batch script (no chances of using DOS binaries today).

> - the cmd extension is used for text files that contain Windows scripts (like bat files) .

I'll add that to the template. But also keep `.com` because of the above reasons (even if I don't remember all the details why it was added, it was the result of a long discussion which lead to that decision).

> To be complete, we should also add `ps1` (file extension for PowerShell script file) in `.gitattributes` and `.editorconfig`.

I didn't include the PS extensions (they are many not just `.ps1`) in this project, but I have them in my snippet templates.

Anyhow, I didn't think any of this would be important — i.e. just expected batch scripts to use `.bat`, which is the common way to do it today. In theory, `.cmd` is the "correct" modern way, but in practice even MS SDKs still use `.bat` mostly.

When I lay hands on the project sources for a new PR I'll tweak the definitions manually and add all the script templates in my arsenal, even if we're not using all these extensions.

**Comment by pml-lang** [comment]
Ok. Thanks.

**Pull request merged**
